var blogTitle = 'Oldest Blog Title';
var blogImg = 'http://static.livedemo00.template-help.com/landing_53775/video/video-bg.jpg';
var blogBody = '<p class="blogP hyphenate">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque et ante purus. In tincidunt pulvinar elementum. Sed dignissim, felis nec suscipit luctus, ante mauris ullamcorper sem, rutrum interdum ipsum turpis in risus. Phasellus sagittis eu purus sit amet tincidunt. Morbi ligula enim, sagittis vitae velit vitae, elementum convallis eros. Mauris non nulla ac lorem facilisis rutrum sit amet in elit. Duis eu egestas ante, ac rhoncus massa. Donec vitae lacinia dolor.</p><p class="blogP hyphenate">Nullam aliquet, mauris consectetur porttitor tempor, dolor magna imperdiet erat, vel vehicula nisl ante sed eros. Cras condimentum felis sapien, nec ultrices lacus semper eget. Mauris elementum diam ut metus mollis, eu suscipit sem lacinia. Vivamus sed aliquet tellus. Maecenas imperdiet vitae lorem non rutrum. Sed volutpat est a purus fermentum vehicula. Aenean non rhoncus libero. Suspendisse diam velit, sollicitudin eu dui ac, bibendum consectetur lacus. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.</p><p class="blogP hyphenate">Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Nam sit amet posuere nulla. Nunc id tristique elit. Vestibulum sit amet varius felis. Mauris porttitor tortor ut tellus efficitur, in sollicitudin libero mattis. Vivamus tortor diam, sodales iaculis rhoncus ut, accumsan quis magna. Quisque et facilisis massa, sit amet auctor libero. Proin eget quam et urna porta aliquam. Suspendisse dignissim condimentum arcu, nec pretium augue luctus eu. Praesent sagittis urna erat, eget facilisis libero finibus quis. Suspendisse hendrerit orci ut hendrerit maximus. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Morbi sodales quis diam vitae volutpat.</p><p class="blogP hyphenate">Duis at sodales nulla. Ut ultricies egestas tortor venenatis rhoncus. Suspendisse lacus justo, euismod volutpat auctor et, faucibus eu urna. Nam ornare augue nec massa aliquet, vitae condimentum diam eleifend. Fusce vitae turpis a leo elementum tristique eget eget velit. Fusce eu turpis at ante dapibus luctus ut vel urna. In eleifend metus risus, tempus eleifend urna aliquet sit amet. Vivamus faucibus nisl ipsum, et viverra nisi vulputate pretium.</p><p class="blogP hyphenate">Aliquam ornare lacus a elit vestibulum, nec pretium odio cursus. Praesent eu magna vehicula, malesuada velit tincidunt, finibus elit. Morbi placerat sapien in purus fermentum, vel molestie neque congue. Curabitur interdum arcu sit amet elit malesuada dapibus.</p>'

var blogModal = '<div class="cmd-modal fade" id="blogModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true"><div class="cmd-modal-dialog" role="document"><div class="cmd-modal-content"><div class="cmd-modal-header"><button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button><h4 class="cmd-modal-title">'+blogTitle+'</h4></div><div class="blog-img"><img alt="" src="http://static.livedemo00.template-help.com/landing_53775/video/video-bg.jpg" class="img-fluid blog-img"></div><div class="cmd-modal-body">'+blogBody+'</div></div></div></div>';
	
	
var blogTitle2 = 'Oldest Blog Title';
var blogImg2 = 'http://static.livedemo00.template-help.com/landing_53775/video/video-bg.jpg';
var blogBody2 = '<p class="blogP hyphenate">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque et ante purus. In tincidunt pulvinar elementum. Sed dignissim, felis nec suscipit luctus, ante mauris ullamcorper sem, rutrum interdum ipsum turpis in risus. Phasellus sagittis eu purus sit amet tincidunt. Morbi ligula enim, sagittis vitae velit vitae, elementum convallis eros. Mauris non nulla ac lorem facilisis rutrum sit amet in elit. Duis eu egestas ante, ac rhoncus massa. Donec vitae lacinia dolor.</p><p class="blogP hyphenate">Nullam aliquet, mauris consectetur porttitor tempor, dolor magna imperdiet erat, vel vehicula nisl ante sed eros. Cras condimentum felis sapien, nec ultrices lacus semper eget. Mauris elementum diam ut metus mollis, eu suscipit sem lacinia. Vivamus sed aliquet tellus. Maecenas imperdiet vitae lorem non rutrum. Sed volutpat est a purus fermentum vehicula. Aenean non rhoncus libero. Suspendisse diam velit, sollicitudin eu dui ac, bibendum consectetur lacus. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.</p><p class="blogP hyphenate">Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Nam sit amet posuere nulla. Nunc id tristique elit. Vestibulum sit amet varius felis. Mauris porttitor tortor ut tellus efficitur, in sollicitudin libero mattis. Vivamus tortor diam, sodales iaculis rhoncus ut, accumsan quis magna. Quisque et facilisis massa, sit amet auctor libero. Proin eget quam et urna porta aliquam. Suspendisse dignissim condimentum arcu, nec pretium augue luctus eu. Praesent sagittis urna erat, eget facilisis libero finibus quis. Suspendisse hendrerit orci ut hendrerit maximus. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Morbi sodales quis diam vitae volutpat.</p><p class="blogP hyphenate">Duis at sodales nulla. Ut ultricies egestas tortor venenatis rhoncus. Suspendisse lacus justo, euismod volutpat auctor et, faucibus eu urna. Nam ornare augue nec massa aliquet, vitae condimentum diam eleifend. Fusce vitae turpis a leo elementum tristique eget eget velit. Fusce eu turpis at ante dapibus luctus ut vel urna. In eleifend metus risus, tempus eleifend urna aliquet sit amet. Vivamus faucibus nisl ipsum, et viverra nisi vulputate pretium.</p><p class="blogP hyphenate">Aliquam ornare lacus a elit vestibulum, nec pretium odio cursus. Praesent eu magna vehicula, malesuada velit tincidunt, finibus elit. Morbi placerat sapien in purus fermentum, vel molestie neque congue. Curabitur interdum arcu sit amet elit malesuada dapibus.</p>'

var blogModal2 = '<div class="cmd-modal fade" id="blogModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true"><div class="cmd-modal-dialog" role="document"><div class="cmd-modal-content"><div class="cmd-modal-header"><button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button><h4 class="cmd-modal-title">'+blogTitle2+'</h4></div><div class="blog-img"><img alt="" src="../../video-bg.jpg" class="img-fluid blog-img"></div><div class="cmd-modal-body">'+blogBody2+'</div></div></div></div>';

var blogTitle3 = 'Newest Blog Title';
var blogImg3 = 'http://static.livedemo00.template-help.com/landing_53775/video/video-bg.jpg';
var blogBody3 =
'<p class="blogP hyphenate">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque et ante purus. In tincidunt pulvinar elementum. Sed dignissim, felis nec suscipit luctus, ante mauris ullamcorper sem, rutrum interdum ipsum turpis in risus. Phasellus sagittis eu purus sit amet tincidunt. Morbi ligula enim, sagittis vitae velit vitae, elementum convallis eros. Mauris non nulla ac lorem facilisis rutrum sit amet in elit. Duis eu egestas ante, ac rhoncus massa. Donec vitae lacinia dolor.</p>' +
'<p class="blogP hyphenate">Nullam aliquet, mauris consectetur porttitor tempor, dolor magna imperdiet erat, vel vehicula nisl ante sed eros. Cras condimentum felis sapien, nec ultrices lacus semper eget. Mauris elementum diam ut metus mollis, eu suscipit sem lacinia. Vivamus sed aliquet tellus. Maecenas imperdiet vitae lorem non rutrum. Sed volutpat est a purus fermentum vehicula. Aenean non rhoncus libero. Suspendisse diam velit, sollicitudin eu dui ac, bibendum consectetur lacus. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.</p>' +
'<p class="blogP hyphenate">Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Nam sit amet posuere nulla. Nunc id tristique elit. Vestibulum sit amet varius felis. Mauris porttitor tortor ut tellus efficitur, in sollicitudin libero mattis. Vivamus tortor diam, sodales iaculis rhoncus ut, accumsan quis magna. Quisque et facilisis massa, sit amet auctor libero. Proin eget quam et urna porta aliquam. Suspendisse dignissim condimentum arcu, nec pretium augue luctus eu. Praesent sagittis urna erat, eget facilisis libero finibus quis. Suspendisse hendrerit orci ut hendrerit maximus. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Morbi sodales quis diam vitae volutpat.</p>' +
'<p class="blogP hyphenate">Duis at sodales nulla. Ut ultricies egestas tortor venenatis rhoncus. Suspendisse lacus justo, euismod volutpat auctor et, faucibus eu urna. Nam ornare augue nec massa aliquet, vitae condimentum diam eleifend. Fusce vitae turpis a leo elementum tristique eget eget velit. Fusce eu turpis at ante dapibus luctus ut vel urna. In eleifend metus risus, tempus eleifend urna aliquet sit amet. Vivamus faucibus nisl ipsum, et viverra nisi vulputate pretium.</p>' +
'<p class="blogP hyphenate">Aliquam ornare lacus a elit vestibulum, nec pretium odio cursus. Praesent eu magna vehicula, malesuada velit tincidunt, finibus elit. Morbi placerat sapien in purus fermentum, vel molestie neque congue. Curabitur interdum arcu sit amet elit malesuada dapibus.</p>';
var blogModal3 =
'<div class="cmd-modal fade" id="blogModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">' +
	'<div class="cmd-modal-dialog" role="document">' +
		'<div class="cmd-modal-content">' +
			'<div class="cmd-modal-header">' +
				'<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>' +
				'<h4 class="cmd-modal-title">' + blogTitle3 + '</h4></div>' +
'<div class="blog-img">' +
'<img alt="" src="' + blogImg3 + '" class="img-fluid blog-img">' +
'</div>' +
'<div class="cmd-modal-body">' +
				blogBody3 +
			'</div>' +
		'</div>' +
	'</div>' +
'</div>';